import Foundation
@testable import GamEngine
import TestSupport
import Testing

/// GamGUI's signature render, curly-quote warning and `show signature` reader, and GAM's own handling of
/// the signature argument (run from the vendored build), held byte for byte to Tests/Fixtures/signatures.json,
/// generated by scripts/gen_fixtures.py.
@Suite("Signatures")
struct SignatureTests {
    struct Render: Decodable { let template: String, user: Int, out: String }
    struct Curly: Decodable { let template: String, warns: Bool }
    struct Shown: Decodable { let text: String, body: String }
    struct Stored: Decodable { let body: String, stored: String }
    struct Keyword: Decodable { let body: String, keyword: Bool }
    struct Gam: Decodable { let file_keywords: [String], stored: [Stored], keyword: [Keyword] }
    struct Document: Decodable {
        let variables: [[String]], seeds: [[String]], render: [Render], smart_quote_warning: String
        let smart_quote: [Curly], parse_signature: [Shown], gam: Gam
    }

    let document = try! JSONDecoder().decode(Document.self, from: Data(contentsOf: Fixtures.signaturesJSON))

    /// The fixture's people, read as the app reads a directory record.
    var users: [GamUser] {
        let data = try! Data(contentsOf: Fixtures.signaturesJSON)
        let records = JSONValue.parse(String(decoding: data, as: UTF8.self))!.object!["users"]!.array!
        return records.map { GamUser(record: $0.object!) }
    }

    private func bytes(_ text: String) -> [UInt8] { Array(text.utf8) }

    @Test func variablesAndSeedsAreGamGUIs() {
        #expect(Signature.variables.map { [$0.token, $0.description] } == document.variables)
        #expect(Signature.seeds.count == document.seeds.count)
        for (seed, expected) in zip(Signature.seeds, document.seeds) {
            #expect(bytes(seed.name) == bytes(expected[0]))
            #expect(bytes(seed.body) == bytes(expected[1]), "\(seed.name)")
        }
    }

    @Test func renderIsGamGUIs() {
        let users = users
        #expect(document.render.count > 1500)
        for item in document.render {
            #expect(bytes(Signature.render(item.template, for: users[item.user])) == bytes(item.out),
                    "\(item.template.debugDescription) for \(users[item.user].primaryEmail)")
        }
    }

    @Test func smartQuoteWarningIsGamGUIs() {
        #expect(document.smart_quote.contains { $0.warns } && document.smart_quote.contains { !$0.warns })
        for item in document.smart_quote {
            #expect(bytes(Signature.smartQuoteWarning(item.template)) == bytes(item.warns ? document.smart_quote_warning : ""),
                    "\(item.template.debugDescription)")
        }
    }

    @Test func parseShownIsGamGUIs() {
        #expect(document.parse_signature.contains { !$0.body.isEmpty })
        for item in document.parse_signature {
            #expect(bytes(Signature.parseShown(item.text)) == bytes(item.body), "\(item.text.debugDescription)")
        }
    }

    /// GAM's `_processSignature`, run from the build: no CR, and each backslash-n pair a `<br/>`.
    @Test func gamStoresTheBodyWithoutCRAndWithBackslashNAsBreaks() {
        #expect(document.gam.stored.contains { $0.body != $0.stored })
        for item in document.gam.stored {
            #expect(bytes(Signature.stored(item.body)) == bytes(item.stored), "\(item.body.debugDescription)")
        }
    }

    /// GAM's own checkArgumentPresent over SORF_FILE_ARGUMENTS, run from the build.
    @Test func aBodyGamReadsAsAKeywordIsRefused() {
        #expect(Signature.fileKeywords == Set(document.gam.file_keywords))
        #expect(document.gam.keyword.contains { $0.keyword } && document.gam.keyword.contains { !$0.keyword })
        for item in document.gam.keyword {
            #expect((Signature.readAsKeyword(item.body) != nil) == item.keyword, "\(item.body.debugDescription)")
        }
    }

    /// Unclosed `[[` and `<` cost GamGUI quadratic time per mailbox before its walks; these stay linear.
    @Test func renderAndQuoteScanAreLinear() {
        let user = users[0]
        let brackets = String(repeating: "[[{title}", count: 16_000)
        let tags = String(repeating: "<\u{201C}", count: 32_000)
        let clock = ContinuousClock()
        let elapsed = clock.measure {
            _ = Signature.render(brackets, for: user)
            _ = Signature.smartQuoteWarning(tags)
            _ = Signature.smartQuoteWarning(String(repeating: "<a>", count: 32_000))
        }
        // About 0.1 s in a debug build here; a walk that rescans from each `[[` or `<` takes minutes.
        #expect(elapsed < .seconds(1), "\(elapsed)")
    }
}
