#!/usr/bin/env python3
"""Generate Packages/GamKit/Sources/GamEngine/PythonHTMLTables.swift from the Python that runs GamGUI.

GamGUI's auto-reply text (core/lifecycle.py autoreply_text) goes through Python's html.unescape, which
reads three tables: the HTML5 named character references (html.entities.html5), the numeric references
the standard remaps (html._invalid_charrefs) and the code points it drops (html._invalid_codepoints).
The Swift port reads the same tables, generated here, never typed. Tests/Fixtures/vacation.json holds
the port to Python's own answers over every name.

Run it with GamGUI's virtualenv Python, as gen_fixtures.py:

    ../gamgui/.venv/bin/python -I -B scripts/gen_html_entities.py
"""

from __future__ import annotations

import html
import sys
from html.entities import html5
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Packages" / "GamKit" / "Sources" / "GamEngine" / "PythonHTMLTables.swift"


def swift_string(text: str) -> str:
    """A Swift string literal that is plain ASCII: every other scalar as \\u{...}."""
    out = []
    for ch in text:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= code < 0x7F:
            out.append(ch)
        else:
            out.append("\\u{%X}" % code)
    return '"' + "".join(out) + '"'


def main() -> int:
    lines = [
        "// Generated by scripts/gen_html_entities.py from Python " + sys.version.split()[0] + ". Do not edit.",
        "// The tables Python's html.unescape reads; held to Tests/Fixtures/vacation.json by HTMLTextTests.",
        "",
        "package enum PythonHTMLTables {",
        "    /// `html.entities.html5`: every HTML5 named character reference, some without their `;`.",
        "    static let html5: [String: String] = [",
    ]
    for name in sorted(html5):
        lines.append(f"        {swift_string(name)}: {swift_string(html5[name])},")
    lines += [
        "    ]",
        "",
        "    /// `html._invalid_charrefs`: numeric references the standard remaps (Windows-1252's 0x80-0x9F, NUL, CR).",
        "    static let invalidCharrefs: [UInt32: String] = [",
    ]
    for code in sorted(html._invalid_charrefs):
        lines.append(f"        0x{code:X}: {swift_string(html._invalid_charrefs[code])},")
    lines += [
        "    ]",
        "",
        "    /// `html._invalid_codepoints`: numeric references that unescape to nothing.",
        "    static let invalidCodepoints: Set<UInt32> = [",
    ]
    codes = sorted(html._invalid_codepoints)
    for start in range(0, len(codes), 8):
        lines.append("        " + ", ".join(f"0x{c:X}" for c in codes[start:start + 8]) + ",")
    lines += ["    ]", "}", ""]
    OUT.write_text("\n".join(lines))
    print(f"{OUT.relative_to(ROOT)}: {len(html5)} names, {len(html._invalid_charrefs)} remapped, {len(codes)} dropped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
